import { describe, expect, it } from 'vitest'
import { ClickAfterDrag } from './click-after-drag.js'

describe('a sidebar drag followed by a click', () => {
  it('swallows the click generated by the drag release', () => {
    const guard = new ClickAfterDrag()

    guard.dragEnded()

    expect(guard.consumeClick()).toBe(true)
    expect(guard.consumeClick()).toBe(false)
  })

  it('does not swallow a later deliberate click when the drag release generated none', () => {
    const guard = new ClickAfterDrag()

    guard.dragEnded()
    guard.pointerStarted()

    expect(guard.consumeClick()).toBe(false)
  })
})
